FROM composer:1.10 AS composer

FROM php:7.4-fpm-alpine AS base

RUN apk add --no-cache icu-dev && \
    docker-php-ext-install pdo_mysql intl

COPY --from=composer /usr/bin/composer /usr/bin/composer
