version: "3.4"

services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=password
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./dist/db:/kunilo
      - data_volume:/var/lib/mysql

  nginx:
    image: nginx:1.19-alpine
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: 
      context: .
      dockerfile: Dockerfile-php
    image: kunilo_php
    restart: unless-stopped
    volumes:
      - ./dist:/api

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025
    restart: unless-stopped

volumes:
  data_volume: {}
